const FETCH_IMG_SAGA = "FETCH_IMG_SAGA"
const DELETE_IMG_SAGA = "DELETE_IMG_SAGA"
const TOGLE_FAVORITE_SAGA = "TOGLE_FAVORITE_SAGA"

export const sagaActions = {
    FETCH_IMG_SAGA,
    DELETE_IMG_SAGA,
    TOGLE_FAVORITE_SAGA
}